services:
  app:
    build:
      context: ../
      dockerfile: deploy/Dockerfile
    command: bash -c "cd src && celery -A tasks worker -l INFO"
    networks:
      - rabbitNetwork

networks:
  rabbitNetwork:
    external: true
    name: rabbitNetwork